import type {
  PlatformAgentDetail,
  PlatformAgentList,
  PlatformAgentRunDiagnostics,
  PlatformAgentRunList,
  PlatformAuditLogList,
  PlatformListPage,
  PlatformReviewBacklog,
  PlatformReviewSummary,
  PlatformSystemHealth,
  PlatformTenantHealth,
  PlatformTenantList,
  PlatformUsage,
} from "../api/platform-schemas";
import { availableSectionContext, freshLiveQuery } from "./platform-overview-fixture";

const selectedWindow = {
  kind: "SELECTED_RANGE" as const,
  from: "2026-08-10T00:00:00.000Z",
  to: "2026-08-11T00:00:00.000Z",
  timeZone: "UTC" as const,
};

const envelope = {
  generatedAt: "2026-08-11T00:00:00.000Z",
  asOf: "2026-08-11T00:00:00.000Z",
  window: selectedWindow,
  freshness: freshLiveQuery,
  partial: false,
  problems: [],
};

export function listPage(overrides: Partial<PlatformListPage> = {}): PlatformListPage {
  return {
    limit: 25,
    hasMore: false,
    nextCursor: null,
    sort: "HEALTH",
    order: "DESC",
    ...overrides,
  };
}

export const tenantListFixture: PlatformTenantList = {
  ...envelope,
  schemaVersion: "platform-tenants.v1",
  filters: { search: null, health: null },
  page: listPage(),
  totals: { matched: 2, healthy: 1, warning: 1, critical: 0, unknown: 0, inactive: 0 },
  items: [
    {
      tenantId: "tenant-breached",
      name: "Breached Construction",
      health: "WARNING",
      reasons: [
        {
          causeId: "cause-review",
          severity: "HIGH",
          title: "Review SLA is breached",
          scope: {
            tenantId: "tenant-breached",
            tenantName: "Breached Construction",
            agentType: null,
            component: null,
          },
          diagnosticsHref: "/platform/review-quality?view=backlog&sla=BREACHED",
          evidenceAt: "2026-08-10T12:00:00.000Z",
        },
      ],
      users: { loggedIn24h: 3, activeAccounts: 12 },
      projects: { total: 4, active: 3 },
      runs: {
        total: 40,
        completed: 34,
        failed: 4,
        degraded: 2,
        rejected: 0,
        stuck: 1,
        completionPercent: 85,
      },
      review: { waiting: 6, breached: 2 },
      aiSpendMicroUsd: 4_200_000,
      storageBytes: 5_242_880,
      lastActivityAt: "2026-08-10T23:00:00.000Z",
      detailHref: "/platform/tenants/tenant-breached/health",
      unknownFields: [],
    },
    {
      tenantId: "tenant-healthy",
      name: "Healthy Builders",
      health: "HEALTHY",
      reasons: [],
      users: { loggedIn24h: 8, activeAccounts: 20 },
      projects: { total: 6, active: 5 },
      runs: {
        total: 30,
        completed: 30,
        failed: 0,
        degraded: 0,
        rejected: 0,
        stuck: 0,
        completionPercent: 100,
      },
      review: { waiting: 0, breached: 0 },
      aiSpendMicroUsd: 1_100_000,
      storageBytes: 1_048_576,
      lastActivityAt: "2026-08-10T22:00:00.000Z",
      detailHref: "/platform/tenants/tenant-healthy/health",
      unknownFields: [],
    },
  ],
};

export const tenantHealthFixture: PlatformTenantHealth = {
  ...envelope,
  schemaVersion: "platform-tenant-health.v1",
  tenant: {
    tenantId: "tenant-breached",
    name: "Breached Construction",
    health: "WARNING",
    createdAt: "2026-01-01T00:00:00.000Z",
    lastActivityAt: "2026-08-10T23:00:00.000Z",
    inactiveDays: 0,
  },
  signals: {
    context: availableSectionContext,
    total: 1,
    items: tenantListFixture.items[0]!.reasons,
  },
  users: {
    context: availableSectionContext,
    activeAccounts: 12,
    suspendedAccounts: 1,
    loggedIn24h: 3,
    loggedIn7d: 9,
    neverLoggedIn: 2,
  },
  agents: {
    context: availableSectionContext,
    total: 1,
    items: [
      {
        agentType: "A1_PROGRESS",
        runs: 40,
        terminal: 40,
        completed: 34,
        failed: 4,
        degraded: 2,
        rejected: 0,
        stuck: 1,
        completionPercent: 85,
        lastSuccessAt: "2026-08-10T22:30:00.000Z",
        costMicroUsd: 4_200_000,
        runsHref: "/platform/agent-runs?tenantId=tenant-breached&agentType=A1_PROGRESS",
      },
    ],
  },
  review: {
    context: availableSectionContext,
    waiting: 6,
    breached: 2,
    withoutDueAt: 1,
    oldestWaitingAt: "2026-08-04T00:00:00.000Z",
    oldestBreachedDueAt: "2026-08-09T00:00:00.000Z",
    backlogHref: "/platform/review-quality?view=backlog&tenantId=tenant-breached",
  },
  delivery: {
    context: availableSectionContext,
    components: [
      {
        component: "OUTBOX",
        state: "DEGRADED",
        required: true,
        summary: "OUTBOX has items requiring attention.",
        metrics: [{ key: "dead_letter", value: 1, unit: "items" }],
        freshness: freshLiveQuery,
        diagnosticsHref: "/platform/system-health?component=OUTBOX&tenantId=tenant-breached",
      },
    ],
  },
  storage: {
    context: availableSectionContext,
    totalBytes: 5_242_880,
    fileCount: 24,
    quarantinedCount: 0,
  },
};

export const agentListFixture: PlatformAgentList = {
  ...envelope,
  schemaVersion: "platform-agents.v1",
  filters: { tenantId: null, state: null },
  page: listPage({ sort: "STATE" }),
  totals: { matched: 2, active: 1, degraded: 1, unknown: 0 },
  items: [
    {
      agentType: "A1_PROGRESS",
      state: "DEGRADED",
      runs: 40,
      terminal: 40,
      completed: 34,
      failed: 4,
      degraded: 2,
      rejected: 0,
      running: 0,
      stuck: 1,
      completionPercent: 85,
      minimumSample: 20,
      p50LatencyMs: 900,
      p95LatencyMs: 4_200,
      retriedRuns: 4,
      retryRatePercent: 10,
      lastSuccessAt: "2026-08-10T22:30:00.000Z",
      costMicroUsd: 4_200_000,
      reasons: [
        {
          causeId: "cause-stuck",
          severity: "HIGH",
          title: "Agent runs are stuck",
          scope: {
            tenantId: null,
            tenantName: null,
            agentType: "A1_PROGRESS",
            component: null,
          },
          diagnosticsHref: "/platform/agent-runs?stuck=true&agentType=A1_PROGRESS",
          evidenceAt: "2026-08-10T23:20:00.000Z",
        },
      ],
      detailHref: "/platform/agents/A1_PROGRESS",
    },
    {
      agentType: "A2_FORECAST",
      state: "ACTIVE",
      runs: 5,
      terminal: 5,
      completed: 4,
      failed: 1,
      degraded: 0,
      rejected: 0,
      running: 0,
      stuck: 0,
      completionPercent: null,
      minimumSample: 20,
      p50LatencyMs: 700,
      p95LatencyMs: 1_400,
      retriedRuns: 0,
      retryRatePercent: 0,
      lastSuccessAt: "2026-08-10T20:00:00.000Z",
      costMicroUsd: 300_000,
      reasons: [],
      detailHref: "/platform/agents/A2_FORECAST",
    },
  ],
};

export const agentDetailFixture: PlatformAgentDetail = {
  ...envelope,
  schemaVersion: "platform-agent-detail.v1",
  filters: { tenantId: null },
  agent: agentListFixture.items[0]!,
  failureBreakdown: {
    context: availableSectionContext,
    items: [
      {
        failureCategory: "PROVIDER",
        count: 4,
        sharePercent: 66.7,
        lastObservedAt: "2026-08-10T23:00:00.000Z",
      },
      { failureCategory: "TIMEOUT", count: 2, sharePercent: 33.3, lastObservedAt: null },
    ],
  },
  tenantBreakdown: {
    context: availableSectionContext,
    items: [
      {
        tenantId: "tenant-breached",
        tenantName: "Breached Construction",
        runs: 40,
        terminal: 40,
        completed: 34,
        failed: 4,
        degraded: 2,
        rejected: 0,
        completionPercent: 85,
        costMicroUsd: 4_200_000,
        healthHref: "/platform/tenants/tenant-breached/health",
      },
    ],
  },
  models: {
    context: availableSectionContext,
    items: [
      {
        provider: "anthropic",
        modelId: "claude-sonnet-5",
        runs: 40,
        costMicroUsd: 4_200_000,
        inputTokens: 90_000,
        outputTokens: 30_000,
      },
    ],
  },
};

export const agentRunListFixture: PlatformAgentRunList = {
  ...envelope,
  schemaVersion: "platform-agent-runs.v1",
  filters: {
    tenantId: null,
    agentType: null,
    status: null,
    outcome: null,
    failureCategory: null,
    stuck: false,
  },
  page: listPage({ sort: "STARTED_AT", hasMore: true, nextCursor: "cursor-page-2" }),
  items: [
    {
      runId: "run-stuck",
      tenantId: "tenant-breached",
      tenantName: "Breached Construction",
      agentType: "A1_PROGRESS",
      status: "RUNNING",
      failureCategory: "NONE",
      trigger: "REQUEST",
      provider: "anthropic",
      modelId: "claude-sonnet-5",
      promptVersion: "a1.v3",
      startedAt: "2026-08-10T22:00:00.000Z",
      completedAt: null,
      latencyMs: 0,
      retryCount: 0,
      costMicroUsd: 90_000,
      costBasis: "ESTIMATED",
      stuck: true,
      diagnosticsHref: "/platform/agent-runs/run-stuck/diagnostics",
    },
    {
      runId: "run-done",
      tenantId: "tenant-healthy",
      tenantName: "Healthy Builders",
      agentType: "A1_PROGRESS",
      status: "COMPLETED",
      failureCategory: "NONE",
      trigger: "SCHEDULE",
      provider: "anthropic",
      modelId: "claude-sonnet-5",
      promptVersion: "a1.v3",
      startedAt: "2026-08-10T21:00:00.000Z",
      completedAt: "2026-08-10T21:01:00.000Z",
      latencyMs: 60_000,
      retryCount: 0,
      costMicroUsd: 110_000,
      costBasis: "ACTUAL",
      stuck: false,
      diagnosticsHref: "/platform/agent-runs/run-done/diagnostics",
    },
  ],
};

export const agentRunDiagnosticsFixture: PlatformAgentRunDiagnostics = {
  ...envelope,
  schemaVersion: "platform-agent-run-diagnostics.v1",
  run: agentRunListFixture.items[1]!,
  execution: {
    requestId: "request-1",
    eventId: null,
    traceId: "trace-1",
    projectId: "project-1",
    toolBundleVersion: "tools.v2",
    outputSchemaVersion: 3,
    dataSnapshotVersion: "snapshot.v9",
    outputSha256: "a".repeat(64),
    contentLoggingEnabled: false,
    asOf: "2026-08-10T20:59:00.000Z",
  },
  usage: {
    inputTokens: 1_200,
    outputTokens: 400,
    cachedInputTokens: 100,
    reasoningTokens: 50,
    estimatedCostMicroUsd: 90_000,
    actualCostMicroUsd: 110_000,
  },
  validation: { state: "PASSED", issueCount: 0 },
  toolCalls: {
    total: 2,
    truncated: false,
    items: [
      {
        id: "call-1",
        toolName: "read_progress",
        status: "SUCCEEDED",
        sequence: 1,
        latencyMs: 120,
        retryCount: 0,
        startedAt: "2026-08-10T21:00:10.000Z",
      },
    ],
  },
  redaction: {
    policy: "platform-diagnostics-redaction.v1",
    redactedFields: ["request", "researchText", "output", "errorMessage"],
    note: "Platform diagnostics expose run metadata only.",
  },
};

export const reviewSummaryFixture: PlatformReviewSummary = {
  ...envelope,
  schemaVersion: "platform-review-summary.v1",
  filters: { tenantId: null },
  backlog: {
    context: availableSectionContext,
    waiting: 6,
    breached: 2,
    withoutDueAt: 1,
    draft: 3,
    oldestWaitingAt: "2026-08-04T00:00:00.000Z",
    oldestBreachedDueAt: "2026-08-09T00:00:00.000Z",
  },
  ageBuckets: {
    context: availableSectionContext,
    items: [
      { bucket: "UNDER_24H", waiting: 3, breached: 0 },
      { bucket: "H24_TO_72H", waiting: 1, breached: 0 },
      { bucket: "D3_TO_D7", waiting: 0, breached: 0 },
      { bucket: "OVER_7D", waiting: 2, breached: 2 },
    ],
  },
  byTenant: {
    context: availableSectionContext,
    items: [
      {
        tenantId: "tenant-breached",
        tenantName: "Breached Construction",
        waiting: 6,
        breached: 2,
        oldestWaitingAt: "2026-08-04T00:00:00.000Z",
        backlogHref: "/platform/review-quality?view=backlog&tenantId=tenant-breached",
      },
    ],
  },
  byTargetType: {
    context: availableSectionContext,
    items: [{ targetType: "DAILY_REPORT", waiting: 6, breached: 2 }],
  },
  throughput: {
    context: availableSectionContext,
    decided: 20,
    approved: 16,
    rejected: 4,
    corrected: 5,
    emergencyOverrides: 1,
    correctionRatePercent: 25,
  },
};

export const reviewBacklogFixture: PlatformReviewBacklog = {
  ...envelope,
  schemaVersion: "platform-review-backlog.v1",
  filters: { tenantId: null, sla: "ALL", targetType: null },
  page: listPage({ sort: "CREATED_AT", order: "ASC" }),
  items: [
    {
      reviewTaskId: "review-breached",
      tenantId: "tenant-breached",
      tenantName: "Breached Construction",
      projectId: "project-1",
      targetType: "DAILY_REPORT",
      targetVersion: 2,
      assignedRole: "SITE_ENGINEER",
      assigned: true,
      status: "REVIEW_REQUIRED",
      createdAt: "2026-08-04T00:00:00.000Z",
      dueAt: "2026-08-09T00:00:00.000Z",
      waitingSeconds: 604_800,
      sla: "BREACHED",
      tenantHref: "/platform/tenants/tenant-breached/health",
    },
  ],
};

export const usageFixture: PlatformUsage = {
  ...envelope,
  schemaVersion: "platform-usage.v1",
  filters: { tenantId: null, agentType: null, groupBy: "TENANT" },
  totals: {
    context: availableSectionContext,
    runs: 70,
    costMicroUsd: 5_300_000,
    actualMicroUsd: 4_000_000,
    estimatedMicroUsd: 1_300_000,
    actualCoveragePercent: 60,
    inputTokens: 120_000,
    outputTokens: 40_000,
    cachedInputTokens: 10_000,
    reasoningTokens: 5_000,
    budgetModel: "NOT_CONFIGURED",
  },
  groups: {
    context: availableSectionContext,
    total: 1,
    truncated: false,
    items: [
      {
        key: "tenant-breached",
        label: "Breached Construction",
        href: "/platform/tenants/tenant-breached/health",
        runs: 40,
        costMicroUsd: 4_200_000,
        actualMicroUsd: 4_000_000,
        estimatedMicroUsd: 200_000,
        actualRunCount: 36,
        estimatedRunCount: 4,
        actualCoveragePercent: 90,
        inputTokens: 90_000,
        outputTokens: 30_000,
        cachedInputTokens: 8_000,
        reasoningTokens: 4_000,
        costSharePercent: 79.2,
      },
    ],
  },
};

export const systemHealthFixture: PlatformSystemHealth = {
  ...envelope,
  schemaVersion: "platform-system-health.v1",
  window: { kind: "SNAPSHOT", from: null, to: "2026-08-11T00:00:00.000Z", timeZone: "UTC" },
  filters: { tenantId: null },
  state: "DEGRADED",
  components: [
    {
      component: "API",
      state: "HEALTHY",
      required: true,
      summary: "The authenticated API request is live.",
      metrics: [],
      freshness: freshLiveQuery,
      diagnosticsHref: "/platform/system-health?component=API",
    },
    {
      component: "OUTBOX",
      state: "DEGRADED",
      required: true,
      summary: "OUTBOX has items requiring attention.",
      metrics: [{ key: "dead_letter", value: 1, unit: "items" }],
      freshness: freshLiveQuery,
      diagnosticsHref: "/platform/system-health?component=OUTBOX",
    },
  ],
  outboxByType: {
    context: availableSectionContext,
    items: [
      {
        eventType: "REPORT_SUBMITTED",
        pending: 4,
        stalled: 2,
        failed: 0,
        deadLetter: 1,
        oldestEvidenceAt: "2026-08-10T23:00:00.000Z",
      },
    ],
  },
  tenantImpact: {
    context: availableSectionContext,
    items: [
      {
        tenantId: "tenant-breached",
        tenantName: "Breached Construction",
        outboxStalled: 2,
        outboxDeadLetter: 1,
        notificationFailed: 0,
        artifactQuarantined: 0,
        healthHref: "/platform/tenants/tenant-breached/health",
      },
    ],
  },
};

export const auditLogFixture: PlatformAuditLogList = {
  ...envelope,
  schemaVersion: "platform-audit-logs.v1",
  filters: {
    tenantId: null,
    actorId: null,
    source: "ALL",
    actorRole: null,
    action: null,
    result: null,
  },
  page: listPage({ sort: "OCCURRED_AT" }),
  items: [
    {
      id: "audit-1",
      actorId: "platform-admin",
      actorDisplayName: "Platform Admin",
      actorRole: "PLATFORM_SUPER_ADMIN",
      action: "PLATFORM_TENANT_HEALTH_READ",
      tenantId: "tenant-breached",
      resourceType: "PLATFORM_TENANT",
      resourceId: "tenant-breached",
      result: "SUCCESS",
      reason: null,
      correlationId: "correlation-1",
      beforeHash: "b".repeat(64),
      afterHash: "c".repeat(64),
      occurredAt: "2026-08-10T23:59:00.000Z",
    },
  ],
};
