ALTER TYPE "RegistrationDraftStatus" ADD VALUE IF NOT EXISTS 'APPLIED';
ALTER TYPE "ReviewTargetType" ADD VALUE IF NOT EXISTS 'REGISTRATION_DRAFT';

ALTER TABLE "RegistrationDraft"
ADD COLUMN "rowVersion" INTEGER NOT NULL DEFAULT 1;
