import type {
  AgentRunEnvelopeV1,
  DailyReportDraftV1,
  ProjectAnalysisSnapshotV1,
} from "../../src/contracts/index.js";

export function buildDailyReportDraft(): DailyReportDraftV1 {
  return {
    schemaVersion: 1,
    draftType: "DAILY_REPORT",
    draftId: "draft-001",
    requestId: "request-001",
    tenantId: "tenant-demo",
    projectId: "project-atlas",
    sourceArtifacts: [],
    rawText: "AT-001 ханын өрлөг 60 хувь, 5 хүн 8 цаг ажиллав.",
    language: "mn",
    reportDate: "2026-03-31",
    location: {
      block: "A блок",
      stage: "Каркас",
      floor: "2",
      zone: null,
    },
    progressEntries: [
      {
        entryId: "progress-draft-001",
        workItem: {
          code: "AT-001",
          name: "Ханын өрлөг",
          candidateCodes: [],
        },
        progressMode: "CUMULATIVE",
        progressPercent: 60,
        quantityDone: "60",
        unit: "м2",
        status: "IN_PROGRESS",
        blocker: null,
        note: "Өнөөдрийн хэмжилтээр баталгаажсан.",
        fieldConfidence: [],
      },
    ],
    attendanceEntries: [
      {
        entryId: "attendance-draft-001",
        teamType: "OWN",
        teamRef: "team-masonry",
        teamName: "Өрлөгийн баг",
        workItemCodes: ["AT-001"],
        headcount: 5,
        hoursPerPerson: 8,
        totalHours: 40,
        fieldConfidence: [],
      },
    ],
    materialSignals: [],
    photoObservations: [],
    clarificationQuestions: [],
    duplicateCandidates: [],
    fieldConfidence: [],
    overallConfidence: 0.91,
    confidenceLevel: "HIGH",
    validationIssues: [],
    status: "READY_FOR_REVIEW",
    requiresHumanReview: true,
  };
}

export function buildProjectAnalysisSnapshot(): ProjectAnalysisSnapshotV1 {
  return {
    schemaVersion: 1,
    snapshotType: "PROJECT_ANALYSIS",
    snapshotId: "snapshot-001",
    tenantId: "tenant-demo",
    projectId: "project-atlas",
    projectCode: "ATLAS",
    projectName: "Atlas барилгын төсөл",
    projectStatus: "ACTIVE",
    asOf: "2026-03-31T00:00:00.000Z",
    activeBaseline: {
      baselineVersionId: "baseline-001",
      version: 1,
      approvedBy: "user-manager",
      approvedAt: "2026-01-01T00:00:00.000Z",
      changeReason: "Анхны батлагдсан суурь төлөвлөгөө",
      plannedStart: "2026-01-05",
      plannedEnd: "2026-06-30",
      budgetMnt: "100000000.00",
      calendar: {
        timezone: "Asia/Ulaanbaatar",
        workingWeekdays: [1, 2, 3, 4, 5, 6],
        workHoursPerDay: 8,
        holidays: ["2026-02-17"],
      },
    },
    workItems: [
      {
        workItemId: "work-item-001",
        parentWorkItemId: null,
        code: "AT-001",
        name: "Ханын өрлөг",
        stage: "Каркас",
        location: "A блок, 2-р давхар",
        unit: "м2",
        plannedQuantity: "100",
        unitCostMnt: "100000.00",
        plannedStart: "2026-03-01",
        plannedEnd: "2026-04-15",
        status: "IN_PROGRESS",
        priority: "HIGH",
        assigneeType: "TEAM",
        assigneeRef: "team-masonry",
        subcontractorId: null,
        isCritical: true,
        displayOrder: 1,
      },
    ],
    dependencies: [],
    materials: [
      {
        materialId: "material-001",
        code: "MAT-BRICK",
        name: "Тоосго",
        aliases: ["улаан тоосго"],
        unit: "ш",
        leadTimeDays: 3,
      },
    ],
    materialNorms: [
      {
        materialNormId: "norm-001",
        workItemId: "work-item-001",
        materialId: "material-001",
        quantityPerWorkUnit: "55",
        wastePercent: 5,
      },
    ],
    subcontractors: [],
    dailyReports: [
      {
        dailyReportId: "report-001",
        date: "2026-03-31",
        reportedBy: "user-engineer",
        rawText: "Ханын өрлөг 60 хувь.",
        status: "APPROVED",
        submittedAt: "2026-03-31T10:00:00.000Z",
        approvedBy: "user-manager",
        approvedAt: "2026-03-31T11:00:00.000Z",
        rejectionReason: null,
        sourceDraftId: "draft-001",
      },
    ],
    progressEntries: [
      {
        progressEntryId: "progress-001",
        dailyReportId: "report-001",
        workItemId: "work-item-001",
        capturedAt: "2026-03-31T10:00:00.000Z",
        quantityDoneIncrement: "10",
        cumulativeQuantityDone: "60",
        progressPercent: 60,
        status: "IN_PROGRESS",
        blockerReason: null,
        note: null,
        aiConfidence: 0.91,
        humanEdited: false,
      },
    ],
    attendanceEntries: [
      {
        attendanceEntryId: "attendance-001",
        dailyReportId: "report-001",
        workItemId: "work-item-001",
        subcontractorId: null,
        teamName: "Өрлөгийн баг",
        headcount: 5,
        hoursPerPerson: 8,
        totalHours: 40,
      },
    ],
    stockMovements: [
      {
        stockMovementId: "stock-001",
        materialId: "material-001",
        kind: "RECEIPT",
        quantity: "4000",
        unitPriceMnt: "1200.00",
        workItemId: null,
        supplierName: "Материал ХХК",
        documentArtifactId: null,
        occurredAt: "2026-03-01T02:00:00.000Z",
        recordedBy: "user-storekeeper",
        reversesMovementId: null,
        reference: "ОР-001",
      },
    ],
    costEntries: [
      {
        costEntryId: "cost-001",
        workItemId: "work-item-001",
        dailyReportId: "report-001",
        category: "LABOR",
        amountMnt: "5000000.00",
        sourceType: "ATTENDANCE",
        sourceId: "attendance-001",
        occurredAt: "2026-03-31T10:00:00.000Z",
        description: "Өрлөгийн багийн хөдөлмөрийн зардал",
      },
    ],
    blockers: [],
    alerts: [],
    forecasts: [],
    recommendationDecisions: [],
    tenantProfile: {
      displayName: "Демо байгууллага",
      terminology: {
        workItem: "ажил",
      },
      blockerCategories: ["MATERIAL", "WEATHER", "LABOR"],
      reportingStyle: "Товч, баримттай Монгол тайлан",
    },
  };
}

export function buildAgentRun(): AgentRunEnvelopeV1 {
  return {
    schemaVersion: 1,
    runId: "run-001",
    requestId: "request-001",
    tenantId: "tenant-demo",
    projectId: "project-atlas",
    agentType: "A2_OBSERVER",
    trigger: "NIGHTLY",
    status: "COMPLETED",
    provider: "openai",
    modelId: "configured-openai-model",
    promptVersion: "a2-v1",
    toolBundleVersion: "readonly-v1",
    inputSchemaVersion: 1,
    outputSchemaVersion: 1,
    dataSnapshotId: "snapshot-001",
    traceId: "trace-001",
    startedAt: "2026-03-31T18:00:00.000Z",
    completedAt: "2026-03-31T18:00:05.000Z",
    retryCount: 0,
    usage: {
      inputTokens: 1_000,
      outputTokens: 300,
      cachedInputTokens: 0,
      reasoningTokens: 0,
      estimatedCostUsd: "0.01",
      toolCallCount: 4,
    },
    outputArtifacts: [],
    error: null,
  };
}
